spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:h2:mem:order-mvp
    username: sa
    password:
    driver-class-name: org.h2.Driver







